---
- hosts: localhost
  connection: localhost
  remote_user: root
  gather_facts: no
  vars_files:
    - awscreds
 
  tasks:
    - name: creating security group for jenkins server
      ec2_group:
        name: jenkins-SG1
        description: this is security group for jenkins
        aws_access_key: "{{access_id}}"
        aws_secret_key: "{{secret_key}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
    
    - name: create a jenkins key
      ec2_key: 
        name: jenkins_key
        aws_access_key: "{{access_id}}"
        aws_secret_key: "{{secret_key}}"
        region: "{{region}}"
      register: jenkins_key

    - debug: 
        msg: "{{jenkins_key.key.private_key}}"
      ignore_errors: true


    - name: save private key
      copy:
        content: "{{jenkins_key.key.private_key}}\n"
        dest: "./jenkins_key.pem"
        mode: 0600
      when: jenkins_key.changed
      ignore_errors: true


    - name: create EC2 instance
      ec2:
        key_name: jenkins_key
        instance_type: t2.micro
        aws_access_key: "{{access_id}}" 
        aws_secret_key: "{{secret_key}}"
        region: "{{region}}"
        image: "{{ami_id}}"
        wait: yes
        wait_timeout: 500
        count: 1
        instance_tags:
             Name: jenkins
             owner: admin
        monitoring: no 
        vpc_subnet_id: "{{vpc_subnet_id}}"
        assign_public_ip: yes
        group: jenkins-SG1
      register: ec2_out
      ignore_errors: true

    - debug:
        msg:  "{{ec2_out.instances[0].public_ip}}"
    - name: name for ssh to comeup
      wait_for: host={{ec2_out.instances[0].public_ip}} port=22 delay=60 timeout=500 state=started

    - name: add instance ip into dynamic inventry file
      add_host:
        hostname: jenkins
        ansible_ssh_host: "{{ec2_out.instances[0].public_ip}}"
        ansible_python_interpreter: /usr/bin/python2.7
        ansible_ssh_private_key_file: jenkins_key.pem
        ansible_ssh_user: ubuntu



    - name: wait for port 22 to be ready
      wait_for: host={{ec2_out.instances[0].public_ip}}  port=22  delay=60 timeout=320 state=started



####################### INSTALLING JENKINS ##########################
        
- hosts: jenkins
  become: yes
  remote_user: root
  gather_facts: false
  tasks:

    - name: install python2.7
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
   
    - name: installing python depencencies
      apt:
        name: "{{item}}"
        state: latest
      with_items:
         - python-pip
         - python-dev

    - name: install packages
      apt:
        update_cache: yes
        name: "{{item}}"
        state: present
      with_items:
        - wget
        - git
        - openjdk-8-jdk
        - maven
      ignore_errors: true


    - name: import jenkins key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
        state: present

    - name: Debian package repository of Jenkins and add key
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        filename: jenkins.list
        state: present


    - name: install jenkins 
      apt:
        name: jenkins
        state: present
       
    - name: disable the firewall
      ufw:
        rule: deny
        state: disabled

