---
- hosts: localhost
  connection: localhost
  remote_user: root
  gather_facts: no
  vars_files:
    - awscreds

  tasks:
    - name: creating security group for nexus server
      ec2_group:
        name: nexus-SG
        description: this is security group for jenkins
        aws_access_key: "{{access_id}}"
        aws_secret_key: "{{secret_key}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 8081
            to_port: 8081
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
    
    - name: create a jenkins key
      ec2_key: 
        name: jenkins_key
        aws_access_key: "{{access_id}}"
        aws_secret_key: "{{secret_key}}"
        region: "{{region}}"
      register: jenkins_key

    - debug: 
        msg: "{{jenkins_key.key.private_key}}"
      ignore_errors: true


    - name: save private key
      copy:
        content: "{{jenkins_key.key.private_key}}\n"
        dest: "./jenkins_key.pem"
        mode: 0600
      when: jenkins_key.changed
      ignore_errors: true


    - name: create EC2 instance
      ec2:
        key_name: jenkins_key
        instance_type: t2.micro
        aws_access_key: "{{access_id}}" 
        aws_secret_key: "{{secret_key}}"
        region: "{{region}}"
        image: "{{ami_id}}"
        wait: yes
        wait_timeout: 500
        count: 1
        instance_tags:
             Name: nexus
             owner: admin
        monitoring: no 
        vpc_subnet_id: "{{vpc_subnet_id}}"
        assign_public_ip: yes
        group: nexus-SG
      register: ec2_out
      ignore_errors: true

    - debug:
        msg:  "{{ec2_out.instances[0].public_ip}}"
    - name: name for ssh to comeup
      wait_for: host={{ec2_out.instances[0].public_ip}} port=22 delay=60 timeout=500 state=started

    - name: add instance ip to ansible grp
      add_host:
        hostname: nexus
        ansible_ssh_host: "{{ec2_out.instances[0].public_ip}}"
        ansible_ssh_user: ubuntu
        ansible_python_interpreter: /usr/bin/python2.7
        groupname: vprohosts


    - name: wait for port 22 to be ready
      wait_for: host={{ec2_out.instances[0].public_ip}}  port=22  delay=60 timeout=320 state=started
        

################################ INSTALLING NEXUS ######################################


- hosts: nexus
  become: yes
  remote_user: root
  gather_facts: false
  tasks:
    - name: install python2.7
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
     
    - name: installing python depencencies
      apt:
        name: "{{item}}"
        state: latest
      with_items:
        - python-pip
        - python-dev


    - name: install jdk
      apt:
        update_cache: yes
        name: openjdk-8-jdk
        state: present
      ignore_errors: yes

    - name: wget the nexus url
      get_url:
        url: http://www.sonatype.org/downloads/nexus-latest-bundle.tar.gz
        dest: /usr/local/

    - name: unzip the tar file
      unarchive:
        src: /usr/local/nexus-2.14.8-01-bundle.tar.gz
        dest: /usr/local/
        remote_src: yes

    - name: creating the softlink 
      file:
        src: /usr/local/nexus-2.14.8-01
        dest: /usr/local/nexus
        state: link



    - name: export the variable
      shell: echo export RUN_AS_USER=root



    - name: stop the nexus
      shell: echo /usr/local/nexus/bin/nexus stop

    - name: start the nexus
      shell: echo /usr/local/nexus/bin/nexus start


    - name: iptables stops
      ufw:
        rule: deny
        state: disabled
